### ISSUE TITLE
Poor man's CSD

### ISSUE THREAD

**Issue by developer91234** [a-parhom/RoundedSBE#14]
https://github.com/jinliu/kwin-deco-chromi

![image](https://github.com/a-parhom/RoundedSBE/assets/43324854/b5d7e039-bb36-426c-b59a-aae37a73f963)

Consider adding the option of having the window decoration cut into where the menubar area usually is. This functionality could be used to make CSD apps look a lot more native on KDE, or just to save space on normal apps by removing the titlebar.

Of course it could be made to look a lot nicer than the implementation I linked.

**Comment by a-parhom** [comment]
The main purpose of this SBE fork is integration of a corner rounding effect with it's configuration window. Currently I don't have any free time for implementing new features.

Any upstream changes or fixes could be merged, though. 

Also, pull requests to this repository are welcome if anybody is willing to implement such feature. 

I'll close this issue for now, since no new features are planned for now.
