### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by sujaldev** [a-parhom/RoundedSBE#17]
After approximately a couple of weeks, the round corners disappear. Then I have to reinstall to get it working again. I'm using fedora 38.

**Comment by DiabeticCrab** [comment]
Installing 3rd party software from source code builds it against the libraries and library versions that are present on your system during compile time.

When you update any of the dependencies of RoundedSBE, this can break it, thus creating a need to recompile and reinstall it.

This is a general issue on UNIXoid operating systems. In Windows, this is prevented by the OS shipping all runtime versions - old and new ones, and nearly all programs being distributed along with compiled versions of their external dependencies that are put into the program folder.

For Linux packages installed via the package manager, the distro maintainers are taking care of that recompiling step for you - that's why those packages don't break every time you install updates.

**Comment by sujaldev** [comment]
Ah, thanks for the explanation! In that case, let me see if I can make an RPM for RoundedSBE and publish it on Fedora COPR.
